"""The canonical data files: a fixed header, registry key order and tomli-w formatting.

Rendering the same data twice gives the same bytes, and `render(read(file)) == file` for every
committed file, which is how every kit step proves it changed nothing (FR-006).
"""

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

import tomli_w

from language_kit.errors import KitUsageError
from language_kit.language_files import EACH, EVALUATION, LanguageData
from language_kit.registry import REQUIREMENTS, Destination, Requirement
from language_kit.voices import VoiceCatalogue

HEADER = (
    "# Generated by the language kit (.claude/skills/language-kit). Do not edit by hand:\n"
    "# change it with a pack (kit.sh backfill / apply). Language: {name} ({code}).\n\n"
)
VOICE_KEY_ORDER = ("key", "display_name", "gender", "locale", "quality", "speaking_rate")
DERIVED_VOICE_KEYS = ("display_name", "locale", "quality")
FIRST_ORDER = 1


@dataclass(frozen=True, slots=True)
class RenderedFiles:
    runtime: str
    evaluation: str | None
    """None when the language has no evaluation values."""


def render(
    language: LanguageData, requirements: Iterable[Requirement] = REQUIREMENTS
) -> RenderedFiles:
    items = tuple(requirements)
    header = HEADER.format(name=language.get("name"), code=language.code)
    runtime = _document(language, items, Destination.RUNTIME)
    evaluation = _document(language, items, Destination.EVALUATION).get(EVALUATION)
    evaluation_text = (
        header + tomli_w.dumps({"code": language.code} | evaluation) if evaluation else None
    )
    return RenderedFiles(header + tomli_w.dumps(runtime), evaluation_text)


def derive(
    language: LanguageData, others: Iterable[LanguageData], catalogue: VoiceCatalogue | None
) -> LanguageData:
    """Fill what a pack never holds: the display order, and a new voice's name, locale and quality."""
    derived = language
    if language.get("order") is None:
        derived = derived.with_value("order", _next_order(others))
    voices = language.get("voices")
    if isinstance(voices, list):
        derived = derived.with_value(
            "voices", [_derived_voice(voice, catalogue) for voice in voices]
        )
    return derived


def _document(
    language: LanguageData, items: tuple[Requirement, ...], where: Destination
) -> dict[str, Any]:
    document = LanguageData(language.code, {})
    for item in items:
        value = language.get(item.path)
        if item.destination is where and EACH not in item.path and value is not None:
            document = document.with_value(item.path, _canonical(item.path, value, items))
    return document.document


def _canonical(path: str, value: Any, items: tuple[Requirement, ...]) -> Any:
    """List-of-table items get a fixed key order: the voice fields, then registry order."""
    fields = [
        item.path.split(f"{EACH}.")[1] for item in items if item.path.startswith(f"{path}{EACH}.")
    ]
    if not fields or not isinstance(value, list):
        return value
    order = [*VOICE_KEY_ORDER, *(field for field in fields if field not in VOICE_KEY_ORDER)]
    return [{key: entry[key] for key in order if key in entry} for entry in value]


def _next_order(others: Iterable[LanguageData]) -> int:
    orders = [other.get("order") for other in others]
    return max((order for order in orders if isinstance(order, int)), default=FIRST_ORDER - 1) + 1


def _derived_voice(voice: Any, catalogue: VoiceCatalogue | None) -> Any:
    if not isinstance(voice, dict) or all(key in voice for key in DERIVED_VOICE_KEYS):
        return voice
    key = voice.get("key")
    candidate = catalogue.voice(str(key)) if catalogue is not None else None
    if candidate is None:
        raise KitUsageError(
            f"voice {key} is not a catalogue voice, so its name and quality are unknown"
        )
    display_name = (
        voice.get("display_name") or f"{candidate.name.capitalize()} ({candidate.country})"
    )
    return voice | {
        "display_name": display_name,
        "locale": candidate.region,
        "quality": candidate.quality,
    }
